### ISSUE TITLE
Issue building core135_start_ui on the MP135

### ISSUE THREAD

**Issue by LispEngineer** [m5stack/M5Stack_Linux_Libs#1]
Hi there,

I have the Core MP135 and the development environment running on it. (Pretty impressive it can host itself.)

Unfortunately, the `core135_start_ui` example program does not work, because it does not have the `ifconfig` function.

Commit: ee5decd69fd7ec132b38c9951195fc9c5d198f95

```
(mp135-first) dfields@M5Core135:~/src/M5Stack_Linux_Libs/examples/core135_start_ui$ ~/src/mp135-first/bin/scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
CXX build/core135_start_ui/main_ui_eth.cpp.o
LD build/core135_start_ui/libcore135_start_ui.a
ranlib build/core135_start_ui/libcore135_start_ui.a
Linking build/core135_start_ui/core135_start_ui
/usr/bin/ld: build/core135_start_ui/libcore135_start_ui.a(main_ui_eth.cpp.o): in function `screen_test_eth_event':
eth.cpp:(.text+0xa6): undefined reference to `ifconfig(std::vector<ifconfig_s, std::allocator<ifconfig_s> >&)'
collect2: error: ld returned 1 exit status
scons: *** [build/core135_start_ui/core135_start_ui] Error 1
scons: building terminated because of errors.
```

I looked around the source herein and see nowhere that the function `ifconfig` is defined.

I was able to comment out the code in `eth.cpp` and otherwise get the example application to build. It also (mostly) runs, as `root`, but not entirely without problems.

Any ideas, please? Thanks!

**Comment by LispEngineer** [comment]
I was able to find a seemingly appropriate `ifconfig.cpp` file [here](https://github.com/ithewei/libhv/blob/031684d58a6199535d0fd3e837d263e4b888ac14/cpputil/ifconfig.cpp). With adding `hv/` to the includes I was able to get the application to build.

Is it possible there are other accidentally omitted `hv` library files as well?

Thanks!

**Comment by dianjixz** [comment]
Please refer to https://github.com/m5stack/M5Stack_Linux_Libs/issues/2.
