### ISSUE TITLE
show_logo example does not compile

### ISSUE THREAD

**Issue by LispEngineer** [m5stack/M5Stack_Linux_Libs#2]
Hi there,

The `show_logo` example does not compile.

```
(mp135-first) dfields@M5Core135:~/src/M5Stack_Linux_Libs/examples/show_logo$ ~/src/mp135-first/bin/s
cons
scons: Reading SConscript files ...
-- Load default: /home/dfields/src/M5Stack_Linux_Libs/examples/show_logo/config_defaults.mk
-- Write makefile config at: /home/dfields/src/M5Stack_Linux_Libs/examples/show_logo/build/config/global_config.mk
-- write  c header file  at: /home/dfields/src/M5Stack_Linux_Libs/examples/show_logo/build/config/global_config.h
-- build type:debug, write DEBUG definition to c header
scons: done reading SConscript files.
scons: Building targets ...
CC build/DeviceDriver/_home_dfields_src_M5Stack_Linux_Libs_components_DeviceDriver_party_framebuffer_fbtools.c.o
LD build/DeviceDriver/libDeviceDriver.a
ranlib build/DeviceDriver/libDeviceDriver.a
CXX build/show_logo/empty_src_file.o
CC build/show_logo/main_src_main.c.o
main/src/main.c:11:10: fatal error: stb_image.h: No such file or directory
   11 | #include "stb_image.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
scons: *** [build/show_logo/main_src_main.c.o] Error 1
scons: building terminated because of errors.
```

It appears the `stb_image.h` is not included in the repo. Is it [this](https://github.com/nothings/stb)?

Are there other dependencies that need to be documented/added?

Commit: ee5decd69fd7ec132b38c9951195fc9c5d198f95

Thanks!

**Comment by LispEngineer** [comment]
FWIW, the `scons menuconfig` shows a `*` next to `Enable stb` under `Components configuration`.

**Comment by dianjixz** [comment]
These are referenced repositories that need to be manually downloaded to the github_source directory. The source-list.sh file in the github_source directory contains the reference links. This allows you to download component repository code as needed and avoid cluttering the development environment. Thank you for the reminder, I will add this explanation to the document later.
