### ISSUE TITLE
lvgl_demo shows just a blank white screen with mouse pointer

### ISSUE THREAD

**Issue by LispEngineer** [m5stack/M5Stack_Linux_Libs#3]
The `lvgl_demo` does not display any text; it seems the `ui_init()` is not called.

If LVGL is supposed to call `ui_init()` automatically, it is not happening. The code does not call it explicitly.

By adding `ui_init();` after `hal_init();` in the `main()` function, the program will now display `hello world` in the center of the screen.

**Comment by dianjixz** [comment]
Thank you very much, it has been fixed.
