### ISSUE TITLE
Update framebuffer_OpenCV

### ISSUE THREAD

**Issue by nnn112358** [m5stack/M5Stack_Linux_Libs#4]
Distributing images from example/framebuffer_OpenCV/img/06b.jpg may infringe copyright. 
I have updated example/framebuffer_OpenCV to avoid the problem. I have made an update to generate a similar colorchart image in OpenCV itself.

https://github.com/nnn112358/M5Stack_Linux_Libs/tree/master/examples/framebuffer_OpenCV

I was going to post this in a pull request, M5Stack_Linux_Libs does not seem to have pull requests open. I posted on this issue.

**Comment by dianjixz** [comment]
Thank you for your reminder; the code will be modified immediately.

**Comment by dianjixz** [comment]
I've tried pull requests, and it should work. You can give it a try. If it fails, could you provide a screenshot of the error?

**Comment by dianjixz** [comment]
I would like to contribute this to you, so I look forward to your pull request.

**Comment by nnn112358** [comment]
Thanks for your response.
